baseURL = "https://mrmateussiilva.github.io/blog/"
languageCode = "pt-br"
title = "~/log"
theme = "paper"

[permalinks.page]
  posts = "/:year/:month/:day/:slug/"

[module]
  [[module.mounts]]
    source = "content"
    target = "content"

  [[module.mounts]]
    source = "2026"
    target = "content/posts/2026"

  [[module.mounts]]
    source = "data"
    target = "data"

  [[module.mounts]]
    source = "layouts"
    target = "layouts"

  [[module.mounts]]
    source = "i18n"
    target = "i18n"

  [[module.mounts]]
    source = "archetypes"
    target = "archetypes"

  [[module.mounts]]
    source = "assets"
    target = "assets"

  [[module.mounts]]
    source = "static"
    target = "static"

[params]
  color = "linen"
  author = "Mateus Silva"
  description = "Engenharia, programação, filosofia e os marcos da minha vida."
  github = "mrmateussiilva"
  twitter = "mrmateusilva"
  linkedin = "mrmateussiilva"

[[menu.main]]
  name = "Sobre"
  url = "/about/"
  weight = 1

[[menu.main]]
  name = "Checkpoints"
  url = "/tags/checkpoint/"
  weight = 2

[[menu.main]]
  name = "Arquivo"
  url = "/posts/"
  weight = 3
